project:
  type: website
  output-dir: "docs/"

website:
  title: "demo-quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual

lang: pt
